Loading pytorch-gpu/py3/1.13.0
  Loading requirement: cuda/11.2 nccl/2.9.6-1-cuda cudnn/8.1.1.33-cuda gcc/8.5.0
    openmpi/4.1.1-cuda intel-mkl/2020.4 magma/2.5.4-cuda-oneapi-mkl sox/14.4.2
    sparsehash/2.0.3 libjpeg-turbo/2.1.3 ffmpeg/N-94431
Unloading cuda/11.2
  Unloading dependent: pytorch-gpu/py3/1.13.0 magma/2.5.4-cuda-oneapi-mkl
    openmpi/4.1.1-cuda cudnn/8.1.1.33-cuda nccl/2.9.6-1-cuda
  Unloading useless requirement: ffmpeg/N-94431 libjpeg-turbo/2.1.3
    sparsehash/2.0.3 sox/14.4.2 intel-mkl/2020.4 gcc/8.5.0
Traceback (most recent call last):
  File "scripts/make_rgb_dataset.py", line 83, in <module>
    main(**vars(args))
  File "scripts/make_rgb_dataset.py", line 48, in main
    scenes_loader = GigaScenesLoader()
  File "/lustre/fswork/projects/rech/tya/ubn15wo/CenterGrasp/centergrasp/giga_utils.py", line 113, in __init__
    p.stem for p in sorted((self.PACKED_TRAIN_PROC / "scenes").iterdir())
  File "/linkhome/rech/genkmw01/ubn15wo/.conda/envs/centergrasp_g_env/lib/python3.8/pathlib.py", line 1122, in iterdir
    for name in self._accessor.listdir(self):
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/fswork/projects/rech/tya/ubn15wo/GIGA/data/packed/40_no_data_packed_train_random_raw_4M_noise/scenes'
